<a href="https://colab.research.google.com/github/stanley7/Machine-Learning/blob/master/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy : Numeric Computing Library
# Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object
# Numpy array can have only one datatype inside an array

In [ ]:
# # Available Data types
# int, float, bool, strings

# np.int16 Integer (-32768 to 32767)
# np.int32 Integer (-2147483648 to 2147483647)
# np.int64 Integer (-9223372036854775808 to 9223372036854775807)

# Numpy overflow
import numpy as np
num_a = np.array([32765, 32766, 32767, 32768], dtype=np.int16)
print(num_a) # Output [ 32765  32766  32767 -32768]
# 32768 gets changes to -32768 because we have overflowed the datatype

# unsigned datatypes
# unsigned datatpes takes only positive values
# np.uint16 Unsigned integer (0 to 65535)
# np.uint32 Unsigned integer (0 to 4294967295)
# np.uint64 Unsigned integer (0 to 18446744073709551615)

# Example: If we give a negetive value we will get an unexpected output
num_b = np.array([-1,0,1], dtype=np.uint16)
print(num_b) # OP [65535     0     1]
# -1 gets changed to 65535

a = np.array([1,1.1,True, 'Hello'])
# Since Numpy array can have only one datatype, it automatically converts every element to String

In [ ]:
# Difference between List and Numpy

# List consumes more memory compared to Numpy 
# Operations in List are slower compared to Numpy
# We can enhance the performance of the list using Numpy array
# List can contain multiple datatypes but Numpy array can have only one datatype

In [ ]:
# Numpy array Shape

# Gives a tuple that specifies the number of rows and columns
a = np.array([1,1.1,True, 'Hello'])
print(a.shape) # (1,4) 

# Numpy array of shape (5,2)
b = np.array([[1,2], [3,4], [5,6],[7,8], [9,10]])
print(b.shape) # (5,2)

In [ ]:
# Get check the data type

num_a = np.array([1,2,3,4.4,True,'Hello'])
print(num_a.dtype)

# Get the size of an array
print(num_a.size) # 6 
print(len(num_a)) # 6

In [ ]:
# To get the dimension of an array ndim

a = np.array([1,1.1,True, 'Hello'])
print(a.ndim) # 1D

a = [1,2,3,4,5]
b = [6,7,8,9,10]
c = [11,12,13,14,15]
d = [16,17,18,19,20]
my_arr = np.array([a,b,c,d])
print(my_arr.ndim) # 2D

arr_3d = np.array([[[ 1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_3d.ndim) # 3D

In [ ]:
# Numpy default values

# Overriding the default datatypes
# To change the datatype of the elements inside an array
a = [[1,2,3], [4,5,6]]
arr = np.array(a, dtype=float)
# Converts all the elements inside an array to float

# Numpy Zeros, Ones and Full methods
print(np.zeros((3,3)))
print(np.ones((3,3))) 
print(np.full((3,3), 5)) # Gives a 3x3 matrix which consits of only element 5
print(np.random.random((3,3))) # Gives a 3x3 matrix of random numbers between 0 and 1

In [ ]:
# Indexing

a = [1,2,3,4,5]
b = [6,7,8,9,10]
c = [11,12,13,14,15]
d = [16,17,18,19,20]
my_arr = np.array([a,b,c,d])

# Output third and fourth elements of all rows
print(my_arr[:, 2:4])

# Output third and fifth element of all rows
print(my_arr[:, 2::2])

# Output the last row
print(my_arr[-1])  # [16 17 18 19 20]
 
# Out the last element of last row
print(my_arr[-1, -1]) # 20

# Output the third row thrid element
print(my_arr[2,2]) # 13

# Output last 2 rows
print(my_arr[-2:])

# Output the first row in reverse
print(my_arr[0, ::-1]) # [5 4 3 2 1]

In [ ]:
# Update, Append, Insert and Delete operations

a = [1,2,3,4,5]
b = [6,7,8,9,10]
c = [11,12,13,14,15]
d = [16,17,18,19,20]
my_arr = np.array([a,b,c,d])

# Update
my_arr[0,4] = 50

# Append

# Append operation in a 1D Array
a = np.array([1,2,3,4,5])
np.append(a, 6) # array([1, 2, 3, 4, 5, 6])
print(a) # It will return the original array [1,2,3,4,5] bcs the values were not stored
a = np.append(a , 6)
print(a) # [1,2,3,4,5,6]

# To append more than 1 element in a 1D array
np.append(a, [7,8]) # array([1, 2, 3, 4, 5, 7, 8])
print(a) # [1,2,3,4,5,6]
a = np.append(a, [7,8]) # Now the values get appended to the original array
print(a) # [1,2,3,4,5,6,7,8]

#Append operation in a 2D Array

two_d = np.array([[1,2,3], [4,5,6]])
np.append(two_d, [7,8,9]) # array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Gives a 1D array

# To append the new values as the last row of the array
np.append(two_d, [[7,8,9]], axis=0)
#array([[1, 2, 3],
#       [4, 5, 6],
#       [7, 8, 9]])

# To append the new values as the last column of the array
np.append(two_d, [[7],[8]], axis=1)
# array([[1, 2, 3, 7],
#       [4, 5, 6, 8]])


# Insert
# Syntax: np.insert(array_name, pos, val)

# Insert a value in a 1D array
one_d = np.array([1,2,3,4,5])
np.insert(one_d, 5, 6) # array([1, 2, 3, 4, 5, 6])

# Insert a value in a 2D array
np.insert(two_d, 6, 7) # array([1, 2, 3, 4, 5, 6, 7])
# Gives a 1D array

# Insert a new column in a 2D array
np.insert(two_d, 2,100, axis=1) 
# array([[  1,   2, 100,   3],
#       [  4,   5, 100,   6]])

np.insert(two_d, 2, [100, 101], axis=1)
#array([[  1,   2, 100,   3],
#       [  4,   5, 101,   6]])

# Insert a new row in a 2D array
np.insert(two_d, 2, 100, axis=0)
#array([[  1,   2,   3],
#       [  4,   5,   6],
#       [100, 100, 100]])

np.insert(two_d, 2 , [[100,101,102]], axis = 0)
#array([[  1,   2,   3],
#       [  4,   5,   6],
#       [100, 101, 102]])

# Delete 

# To delete an element in a 1D array
np.delete(one_d, 0) # array([2, 3, 4, 5])



In [73]:

# Boolean
# Check if the values inside the array is greater than 5

val = my_arr > 5
print(val)
''' Output
[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
'''

# Print out the values which are returned True by the previous condition
print(my_arr[val])  # [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
# It returns a 1D array

# Print out the values which are returned previous condition
# Retaining the original shape of the array
# Replace True by 1 and False by 0
print(np.where(my_arr>5, 1, 0)) # Using where
''' 
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
'''

# Print out the values which are returned by the previous condition
# Retaining the original shape of the array
# Print only the elements which are True and replace False by 0
print(np.where(my_arr>5, my_arr, 0))
'''
[[ 0  0  0  0  0]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
'''

# Print out the values which are returned by the previous condition
# Retaining the original shape of the array
# Print only the elements which are False and replace True by 1
print(np.where(my_arr>5, 1, my_arr))
'''
[[1 2 3 4 5]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
'''

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[50  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[0 0 0 0 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[ 0  0  0  0 50]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[1 2 3 4 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


'\n[[1 2 3 4 5]\n [1 1 1 1 1]\n [1 1 1 1 1]\n [1 1 1 1 1]]\n'

In [ ]:
# logical and
# To check the multiple condition in a array

print(np.logical_and(my_arr>5, my_arr<15)) # Returns boolean value
'''
[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True False]
 [False False False False False]]
'''